POST http://localhost:8000/band_create/
Content-Type: application/json

{
   "name":"boards of Canada",
   "genre" :"Electronic" ,
   "album" :[
    {
        "title":"Boards of Canada",
        "releasedDate":"2010-12-30"
    },
    {
        "title":"Dreamland",
        "releasedDate":"2015-02-03"
    }
   ]
}
